### ISSUE TITLE
Sidebars for Pages ready

### ISSUE THREAD

**Issue by wdet30** [arsmentis/wdet-conversion#30]
Hello, we do have a solution for Sidebars.

**Comment by wdet30** [comment]
Working on this now.

**Comment by metastange** [comment]
@wdet30  - Issue #55 is the donation modules, so I'm unclear how sidebars have been set up with the feedback provided there.

I also do not see any sidebars to review - please clarify where I should be looking.

**Comment by metastange** [comment]
Also, adding an additional sidebar request: can we get a "more about WDET" sidebar that can be used on things like the job page, etc?

### More About WDET
Programming & Mission

Ways To Listen

Meet Our Staff 

Join Our Team 

Ways To Give

Become A Sponsor

Station Blog

Public File

Contact Us

Help/FAQ

**Comment by wdet30** [comment]
Got it, will update over the weekend.



________________________________

**Comment by wdet30** [comment]
@metastange @dorothyhernandez , this info will not be available in sidebars anymore:

**Music/Show Pages**
- Show time(s)
- Hosted By
- Social links/email contact (if pertinent)
- Podcast Pages

**Hosted By**
- Pod platform links (Apple Podcast, Spotify, NPR, Google Podcasts)

Moving forward this info will need to be in the body of the page. Underneath the show banner.

Please make task to update all show and info pages  with this info:
**Music/Show Pages**
- Show time(s)
- Hosted By
- Social links/email contact (if pertinent)
- Podcast Pages

**Hosted By**
- Pod platform links (Apple Podcast, Spotify, NPR, Google Podcasts)
Tony

**Comment by metastange** [comment]
@wdet30 What will be in the sidebars, then?

**Comment by wdet30** [comment]
Sidebars are live, I will get you links so you can see what is what. Give me a few.

**Comment by wdet30** [comment]
@metastange, I noticed the old site had the show time and host info in the sidebar. I wanted to put tis data underneath banner in the new site. If you need that data in the side bar for every show or series, it will take about a day or so. I can make it happen. please advise. 

Here are the current sidebars proposed for launch.

**An example of a post page and sidebar: (Generic sidebar)**
https://wdetcms.wdet.org/2021/10/19/city-of-detroit-prepares-to-open-talks-with-residents-on-budget
**Station Pages**
https://wdetcms.wdet.org/support-detroits-public-radio-station
**Show and Music Pages**
https://wdetcms.wdet.org/wdet-podcasts

**Comment by metastange** [comment]
Are you looking for style feedback or just feedback on the content?

**Comment by wdet30** [comment]
I will take both.

**Comment by metastange** [comment]
It's fine to omit the show time, but would like to include host including pertinent links and contact info in the sidebars if possible. Screenshot of what I have in mind:
![show host sidebar info](https://user-images.githubusercontent.com/85897115/139713700-09d455e5-69c1-41a7-ad8d-98d437d03f85.jpg)

Global:
- Stylistically, not loving the shadowing on the boxes; it makes the pages look disconnected.
- Email opt-in should match what's currently on site (COPY: Stay connected to Detroit. Subscribe to receive WDET’s weekly newsletters: // remove first name field // aligne check boxes and newsletter names)

Generic post page sidebar:
- Search function says "Search wdet.org" on this, but not on the show page version
- Do we need to include search if it's in the nav? Seems redundant
- Remove "Archives" - this is not really a helpful search function in this capacity

Station Pages
- "Donate to WDET" button should have white text
- Add newsletter opt-in
- The ad size looks different than the 300 x 250 on other pages; is that the case?

Show and Music pages:
- Search function is just a search bar instead of includeing copy "Search wdet.org" like on the post page
- Do we need to include search if it's in the nav? Seems redundant
- Remove "Archives"
- Remove "Recently Played Songs" playlist - shows up weird in mobile and i don't know that this needs to be viewable on all of the show/podcast/landing pages, especially since there's already another playlist on many of those pages; maybe just include "recently played" playlist in the "WDET Shows" landing page sidebar?

**Comment by wdet30** [comment]
Got the list.

TB
________________________________

**Comment by wdet30** [comment]
@metastange, just noticed a bug in the sidebars. I'm taking out of Q&A and moving to important bug.

**Comment by metastange** [comment]
@wdet30 has this sidebar bug been resoolved? If so, can we close this?

**Comment by wdet30** [comment]
Yes resolved

________________________________
