### ISSUE TITLE
Series pages ready for review

### ISSUE THREAD

**Issue by wdet30** [arsmentis/wdet-conversion#51]
@metastange @dorothyhernandez , it seems these pages need some TLC.

https://layout.wdet.org/series/

Looking to verify:
• Series banner
• Series times
• Description of Series
• Link to Series and or host.
• Blog post widget. (Querying the latest posts of the Series or podcast. IE: blog post to category)
• Playlist widget if it is a Series.
• Donation template
• Please report any styling issues or missing Series information. Did I miss any Series?
https://layout.wdet.org/series/

**Comment by metastange** [comment]
My QA notes have been added to the doc. Most updates are really minor, just spacing issues and missing content blocks.

One large outstanding question I have applies to series, show and podcast landing pages:
The short descriptions on the show landing page does not match what we have on the current site; it appears it is just pulling in the text from the page. Are we able to customize the text that populates on the show page? 

Please advise.

**Comment by wdet30** [comment]
Looking on this now

**Comment by metastange** [comment]
All content/formatting updates have been made. I'm just waiting on assets for Community of Hope, but otherwise we're good to go on our end. @wdet30 I just need you to add the related content blocks. Open items highlighted in red in the QA doc:

https://docs.google.com/spreadsheets/d/1Mn3GE9EvKJ2Mokv0kmrI4HsnmTZu_zTXYrq8uK150sw/edit#gid=1753176895
